teleport:
  request-timeout-seconds: 60
  rtp-cooldown-seconds: 60
  rtp-radius: 2000
  rtp-attempts: 10
  rtp-world-whitelist:
    - world
homes:
  max-per-player: 3
economy:
  allow-partial-convert: false
  max-convert-per-op: 4096
party:
  invite-timeout-seconds: 60
database:
  file: plugins/lkjmcsmp/lkjmcsmp.db
